export const mockStaff = [
  {
    id: "1",
    name: "Sarah Mitchell",
    firstName: "Sarah",
    lastName: "Mitchell",
    roles: ["Senior Sales Rep", "Team Lead"],
    department: "Sales",
    lineManager: "Alice Thompson",
    email: "sarah.mitchell@company.com",
    phone: "7700 900 001",
    sentinelId: "SNT-00101",
    calls: 142,
    avgScore: 92,
    status: "active",
  },
  {
    id: "2",
    name: "James Walker",
    firstName: "James",
    lastName: "Walker",
    roles: ["Sales Rep"],
    department: "Sales",
    lineManager: "Alice Thompson",
    email: "james.walker@company.com",
    phone: "7700 900 002",
    sentinelId: "SNT-00102",
    calls: 98,
    avgScore: 78,
    status: "active",
  },
  {
    id: "3",
    name: "Emily Chen",
    firstName: "Emily",
    lastName: "Chen",
    roles: ["Customer Support", "Team Lead"],
    department: "Customer Support",
    lineManager: "Carol Davies",
    email: "emily.chen@company.com",
    phone: "7700 900 003",
    sentinelId: "SNT-00103",
    calls: 210,
    avgScore: 85,
    status: "active",
  },
  {
    id: "4",
    name: "Marcus Johnson",
    firstName: "Marcus",
    lastName: "Johnson",
    roles: ["Sales Rep"],
    department: "Sales",
    lineManager: "Bob Harris",
    email: "",
    phone: "7700 900 004",
    sentinelId: "",
    calls: 76,
    avgScore: 64,
    status: "review",
  },
  {
    id: "5",
    name: "Olivia Brown",
    firstName: "Olivia",
    lastName: "Brown",
    roles: ["Senior Sales Rep"],
    department: "Retention",
    lineManager: "Alice Thompson",
    email: "olivia.brown@company.com",
    phone: "",
    sentinelId: "SNT-00105",
    calls: 185,
    avgScore: 91,
    status: "active",
  },
  {
    id: "6",
    name: "Daniel Kim",
    firstName: "Daniel",
    lastName: "Kim",
    roles: ["Customer Support", "Manager"],
    department: "Customer Support",
    lineManager: "Carol Davies",
    email: "daniel.kim@company.com",
    phone: "7700 900 006",
    sentinelId: "SNT-00106",
    calls: 162,
    avgScore: 88,
    status: "active",
  },
];

export const mockReports = [
  { id: "r1", staffId: "1", date: "2026-05-07", score: 94, callType: "Sales Call", focus: "Closing Technique", status: "completed" },
  { id: "r2", staffId: "1", date: "2026-05-04", score: 91, callType: "Follow-up", focus: "Communication", status: "completed" },
  { id: "r3", staffId: "1", date: "2026-04-28", score: 89, callType: "Product Demo", focus: "Product Knowledge", status: "completed" },
  { id: "r4", staffId: "2", date: "2026-05-06", score: 78, callType: "Sales Call", focus: "Objection Handling", status: "completed" },
  { id: "r5", staffId: "2", date: "2026-04-30", score: 74, callType: "Follow-up", focus: "Overall Performance", status: "completed" },
  { id: "r6", staffId: "3", date: "2026-05-06", score: 88, callType: "Support Call", focus: "Communication", status: "completed" },
  { id: "r7", staffId: "3", date: "2026-05-01", score: 82, callType: "Complaint", focus: "Overall Performance", status: "completed" },
  { id: "r8", staffId: "4", date: "2026-05-05", score: 64, callType: "Sales Call", focus: "Closing Technique", status: "needs_review" },
  { id: "r9", staffId: "5", date: "2026-05-05", score: 93, callType: "Sales Call", focus: "Overall Performance", status: "completed" },
  { id: "r10", staffId: "5", date: "2026-04-29", score: 90, callType: "Product Demo", focus: "Product Knowledge", status: "completed" },
  { id: "r11", staffId: "6", date: "2026-05-04", score: 87, callType: "Support Call", focus: "Communication", status: "completed" },
  { id: "r12", staffId: "6", date: "2026-04-27", score: 89, callType: "Support Call", focus: "Overall Performance", status: "completed" },
];