name: Sync Replicas

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: CoreEnvironment
    steps:
      - name: Checkout master repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          
      - name: Push to replica-1
        env:
          GH_USERNAME: RoAtDeploy
          GH_TOKEN: ${{ secrets.CORE_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add replica-1 "https://${GH_USERNAME}:${GH_TOKEN}@github.com/RoAtDeploy/critcom301-replica-1.git"

          git remote -v
          git push --mirror replica-1

      - name: Push to replica-2
        env:
          GH_USERNAME: RoAtDeploy
          GH_TOKEN: ${{ secrets.CORE_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add replica-2 "https://${GH_USERNAME}:${GH_TOKEN}@github.com/RoAtDeploy/critcom301-replica-2.git"

          git remote -v
          git push --mirror replica-2

      - name: Push to syncbase
        env:
          GH_USERNAME: RoAtDeploy
          GH_TOKEN: ${{ secrets.CORE_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote add syncbase "https://${GH_USERNAME}:${GH_TOKEN}@github.com/RoAtDeploy/syncbase.git"

          git remote -v
          git push --mirror syncbase
