name: Sync Replicas

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to replica-1
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push --mirror https://x-access-token:${{ secrets.SYNC_REPLICA_TOKEN }}@github.com/RoAtDeploy/critcom301-replica-1.git
        continue-on-error: true
